site_name: Django Messages DRF
site_description: The little library for a DRF message box and a little effort.

repo_name: tarsil/django-messages-drf
repo_url: https://github.com/tarsil/django-messages-drf
edit_uri: ""


theme:
  name: material
  features:
    - navigation.expand

  palette:
    # Toggle light mode
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Introduction: 'index.md'
  - Overview:
    - 'installation.md'
    - 'overview/reference-guide.md'
    - 'overview/url-names.md'
    - 'overview/views.md'
    - 'overview/signals.md'
  - Views: 'views.md'
  - Release Notes: 'release-notes.md'