# Generated by Django 3.2.8 on 2022-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userthread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
